import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lucide_icons/lucide_icons.dart';

import '../../../core/extensions/context_extensions.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_spacing.dart';
import '../../../core/theme/app_surfaces.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../providers/core_providers.dart';

class NotificationSettingsScreen extends ConsumerStatefulWidget {
  const NotificationSettingsScreen({super.key});

  @override
  ConsumerState<NotificationSettingsScreen> createState() =>
      _NotificationSettingsScreenState();
}

class _NotificationSettingsScreenState
    extends ConsumerState<NotificationSettingsScreen> {
  // BILL ALERTS
  bool _billDueSoon = true;
  bool _billOverdue = true;
  bool _paymentRecorded = true;
  bool _budgetThresholdExceeded = false;
  // BILL GENERATION
  bool _newBillAdded = true;
  bool _billAutoGenerated = true;
  bool _preGenerationWarning = false;
  // SERVICE ACTIVITY
  bool _serviceAdded = false;
  bool _serviceUpdated = false;
  // ACCOUNT
  bool _emailVerification = true;
  bool _generalNotifications = true;

  bool _loading = true;
  bool _saving = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    final repo = ref.read(profileRepositoryProvider);
    try {
      final profile = await repo.getProfile();
      final p = profile?.notificationPrefs ?? const <String, dynamic>{};
      if (!mounted) return;
      setState(() {
        _billDueSoon = p['bill_due_soon'] as bool? ?? true;
        _billOverdue = p['bill_overdue'] as bool? ?? true;
        _paymentRecorded = p['payment_recorded'] as bool? ?? true;
        _budgetThresholdExceeded = p['budget_threshold_exceeded'] as bool? ?? false;
        _newBillAdded = p['new_bill_added'] as bool? ?? true;
        _billAutoGenerated = p['bill_auto_generated'] as bool? ?? true;
        _preGenerationWarning = p['pre_generation_warning'] as bool? ?? false;
        _serviceAdded = p['service_added'] as bool? ?? false;
        _serviceUpdated = p['service_updated'] as bool? ?? false;
        _emailVerification = p['email_verification'] as bool? ?? true;
        _generalNotifications = p['general_notifications'] as bool? ?? true;
      });
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _save() async {
    setState(() => _saving = true);
    try {
      final repo = ref.read(profileRepositoryProvider);
      await repo.updateProfile({
        'notification_prefs': {
          'bill_due_soon': _billDueSoon,
          'bill_overdue': _billOverdue,
          'payment_recorded': _paymentRecorded,
          'budget_threshold_exceeded': _budgetThresholdExceeded,
          'new_bill_added': _newBillAdded,
          'bill_auto_generated': _billAutoGenerated,
          'pre_generation_warning': _preGenerationWarning,
          'service_added': _serviceAdded,
          'service_updated': _serviceUpdated,
          'email_verification': _emailVerification,
          'general_notifications': _generalNotifications,
        },
      });
      if (mounted) {
        context.showSnackBar('Notification preferences saved');
      }
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return Scaffold(
        backgroundColor: Colors.transparent,
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        scrolledUnderElevation: 0,
        title: const Text('Notifications'),
      ),
      body: ListView(
        padding: const EdgeInsets.fromLTRB(
            AppSpacing.base, AppSpacing.sm, AppSpacing.base, 120),
        children: [
          // BILL ALERTS
          _SectionLabel(label: 'BILL ALERTS'),
          const SizedBox(height: AppSpacing.sm),
          _NotifGroup(
            tiles: [
              _NotifTile(
                icon: LucideIcons.clock,
                iconColor: AppColors.warning,
                title: 'Bill Due Soon',
                subtitle: 'Remind me before a bill is due.',
                value: _billDueSoon,
                onChanged: (v) => setState(() => _billDueSoon = v),
              ),
              _NotifTile(
                icon: LucideIcons.alertTriangle,
                iconColor: AppColors.error,
                title: 'Bill Overdue',
                subtitle: 'Alert me when a bill is past due.',
                value: _billOverdue,
                onChanged: (v) => setState(() => _billOverdue = v),
              ),
              _NotifTile(
                icon: LucideIcons.checkCircle,
                iconColor: AppColors.success,
                title: 'Payment Recorded',
                subtitle: 'Notify when a payment is logged.',
                value: _paymentRecorded,
                onChanged: (v) => setState(() => _paymentRecorded = v),
              ),
              _NotifTile(
                icon: LucideIcons.trendingUp,
                iconColor: AppColors.teal,
                title: 'Budget Threshold Exceeded',
                subtitle: 'Warn when spending exceeds my budget.',
                value: _budgetThresholdExceeded,
                onChanged: (v) => setState(() => _budgetThresholdExceeded = v),
              ),
            ],
          ).animate().fadeIn(delay: 50.ms),
          const SizedBox(height: AppSpacing.lg),

          // BILL GENERATION
          _SectionLabel(label: 'BILL GENERATION'),
          const SizedBox(height: AppSpacing.sm),
          _NotifGroup(
            tiles: [
              _NotifTile(
                icon: LucideIcons.plusCircle,
                iconColor: AppColors.primary,
                title: 'New Bill Added',
                subtitle: 'Notify when a new bill is created.',
                value: _newBillAdded,
                onChanged: (v) => setState(() => _newBillAdded = v),
              ),
              _NotifTile(
                icon: LucideIcons.cpu,
                iconColor: AppColors.purple,
                title: 'Bill Auto-Generated',
                subtitle: 'Alert me when AI generates a bill automatically.',
                value: _billAutoGenerated,
                onChanged: (v) => setState(() => _billAutoGenerated = v),
              ),
              _NotifTile(
                icon: LucideIcons.bell,
                iconColor: AppColors.info,
                title: 'Pre-Generation Warning',
                subtitle: 'Remind me before scheduled auto-generation.',
                value: _preGenerationWarning,
                onChanged: (v) => setState(() => _preGenerationWarning = v),
              ),
            ],
          ).animate().fadeIn(delay: 100.ms),
          const SizedBox(height: AppSpacing.lg),

          // SERVICE ACTIVITY
          _SectionLabel(label: 'SERVICE ACTIVITY'),
          const SizedBox(height: AppSpacing.sm),
          _NotifGroup(
            tiles: [
              _NotifTile(
                icon: LucideIcons.packagePlus,
                iconColor: AppColors.teal,
                title: 'Service Added',
                subtitle: 'Notify when a new service is added.',
                value: _serviceAdded,
                onChanged: (v) => setState(() => _serviceAdded = v),
              ),
              _NotifTile(
                icon: LucideIcons.refreshCw,
                iconColor: AppColors.warning,
                title: 'Service Updated',
                subtitle: 'Alert when service details change.',
                value: _serviceUpdated,
                onChanged: (v) => setState(() => _serviceUpdated = v),
              ),
            ],
          ).animate().fadeIn(delay: 150.ms),
          const SizedBox(height: AppSpacing.lg),

          // ACCOUNT
          _SectionLabel(label: 'ACCOUNT'),
          const SizedBox(height: AppSpacing.sm),
          _NotifGroup(
            tiles: [
              _NotifTile(
                icon: LucideIcons.mail,
                iconColor: AppColors.primary,
                title: 'Email Verification',
                subtitle: 'Alerts for email changes and confirmations.',
                value: _emailVerification,
                onChanged: (v) => setState(() => _emailVerification = v),
              ),
              _NotifTile(
                icon: LucideIcons.bell,
                iconColor: const Color(0xFF596063),
                title: 'General Notifications',
                subtitle: 'Product updates and announcements.',
                value: _generalNotifications,
                onChanged: (v) => setState(() => _generalNotifications = v),
              ),
            ],
          ).animate().fadeIn(delay: 200.ms),
          const SizedBox(height: AppSpacing.xl),

          // Save button
          FilledButton(
            onPressed: _saving ? null : _save,
            style: FilledButton.styleFrom(
              backgroundColor: AppColors.primary,
              minimumSize: const Size.fromHeight(48),
              shape: const StadiumBorder(),
            ),
            child: _saving
                ? const SizedBox(
                    width: 18,
                    height: 18,
                    child: CircularProgressIndicator(
                        strokeWidth: 2, color: Colors.white),
                  )
                : const Text('Save Preferences'),
          ).animate().fadeIn(delay: 250.ms),
        ],
      ),
    );
  }
}

// ── Section Label ─────────────────────────────────────────────────────────────

class _SectionLabel extends StatelessWidget {
  const _SectionLabel({required this.label});
  final String label;

  @override
  Widget build(BuildContext context) {
    return Text(
      label,
      style: AppTextStyles.labelSm.copyWith(
        color: Theme.of(context).colorScheme.onSurfaceVariant,
        letterSpacing: 0.6,
        fontWeight: FontWeight.w700,
      ),
    );
  }
}

// ── Notification Group (card container) ───────────────────────────────────────

class _NotifGroup extends StatelessWidget {
  const _NotifGroup({required this.tiles});
  final List<_NotifTile> tiles;

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: AppSurfaces.panel(context),
        borderRadius: BorderRadius.circular(16),
        border: AppSurfaces.cardBorder(context),
        boxShadow: AppSurfaces.softShadow(context),
      ),
      child: Column(
        children: [
          for (int i = 0; i < tiles.length; i++) ...[  
            tiles[i],
            if (i < tiles.length - 1)
              const Divider(height: 1, indent: 56, endIndent: 16),
          ],
        ],
      ),
    );
  }
}

// ── Single Notification Toggle Row ────────────────────────────────────────────

class _NotifTile extends StatelessWidget {
  const _NotifTile({
    required this.icon,
    required this.iconColor,
    required this.title,
    required this.subtitle,
    required this.value,
    required this.onChanged,
  });

  final IconData icon;
  final Color iconColor;
  final String title;
  final String subtitle;
  final bool value;
  final ValueChanged<bool> onChanged;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.md, vertical: 12),
      child: Row(
        children: [
          Container(
            width: 36,
            height: 36,
            decoration: BoxDecoration(
              color: iconColor.withOpacity(0.12),
              borderRadius: BorderRadius.circular(10),
            ),
            child: Icon(icon, size: 16, color: iconColor),
          ),
          const SizedBox(width: AppSpacing.md),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: AppTextStyles.body.copyWith(
                    fontWeight: FontWeight.w600,
                    color: Theme.of(context).colorScheme.onSurface,
                  ),
                ),
                Text(
                  subtitle,
                  style: AppTextStyles.bodySm.copyWith(
                    color: Theme.of(context).colorScheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
          Switch.adaptive(
            value: value,
            onChanged: onChanged,
            activeTrackColor: AppColors.primary,
            thumbColor: WidgetStateProperty.resolveWith((states) =>
                states.contains(WidgetState.selected) ? Colors.white : null),
          ),
        ],
      ),
    );
  }
}
