// Copyright (c) 2025 Ishan Chakraborty. All rights reserved.
// YesBill -- Daily Billing Tracker | Created by Ishan Chakraborty

import { motion } from "framer-motion";

export default function PageHero({ title, subtitle, children }) {
  return (
    <section className="relative pt-36 pb-20 px-6 overflow-hidden">
      <div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-12 items-center">
        {/* Left Content */}
        <motion.div
           initial={{ opacity: 0, x: -30 }}
           animate={{ opacity: 1, x: 0 }}
           transition={{ duration: 0.6 }}
        >
          <motion.h1 
            className="text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 mb-6 leading-tight"
          >
            {title}
          </motion.h1>
          <motion.p 
            className="text-xl text-gray-500 mb-8 max-w-lg leading-relaxed"
          >
            {subtitle}
          </motion.p>
          
          {/* Optional CTA Slot */}
          <div className="flex gap-4">
             {children}
          </div>
        </motion.div>

        {/* Right Content - Abstract Billing Graphic */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9, rotate: -2 }}
          animate={{ opacity: 1, scale: 1, rotate: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="relative hidden lg:block"
        >
          <div className="relative z-10 bg-white/60 backdrop-blur-xl border border-white/40 rounded-3xl p-6 shadow-2xl shadow-indigo-500/10 ring-1 ring-black/5 transform rotate-2 hover:rotate-0 transition-transform duration-500">
               {/* Header Mock */}
               <div className="flex justify-between items-center mb-8 border-b border-gray-200/50 pb-4">
                  <div className="flex items-center gap-3">
                     <div className="w-10 h-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold">YB</div>
                     <div>
                       <div className="text-sm font-bold text-gray-900">Invoice #0024</div>
                       <div className="text-xs text-gray-400">Oct 01 - Oct 31</div>
                     </div>
                  </div>
                  <div className="text-right">
                     <div className="text-xs text-gray-400 uppercase font-bold">Total Due</div>
                     <div className="text-2xl font-bold text-gray-900">₹2,450</div>
                  </div>
               </div>

               {/* Line Items */}
               <div className="space-y-3">
                  {[1, 2, 3].map((i) => (
                    <div key={i} className="flex justify-between items-center p-3 bg-white rounded-xl shadow-sm border border-gray-100">
                       <div className="flex items-center gap-3">
                          <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${i===1?'bg-blue-100 text-blue-500': i===2?'bg-orange-100 text-orange-500':'bg-green-100 text-green-500'}`}>
                             {i===1 ? '🥛' : i===2 ? '📰' : '🧹'}
                          </div>
                          <div>
                             <div className="text-sm font-semibold text-gray-900">{i===1 ? 'Milk' : i===2 ? 'Newspaper' : 'Cleaning'}</div>
                             <div className="text-xs text-gray-400">Daily Service</div>
                          </div>
                       </div>
                       <div className="font-semibold text-gray-900">
                          {i===1 ? '₹1,500' : i===2 ? '₹250' : '₹700'}
                       </div>
                    </div>
                  ))}
               </div>

               <div className="mt-6 pt-4 border-t border-gray-200/50 flex justify-between items-center">
                  <div className="text-xs text-gray-400">Auto-generated by YesBill</div>
                  <div className="bg-green-500 text-white text-xs px-3 py-1 rounded-full font-bold shadow-lg shadow-green-500/20">PAID</div>
               </div>
          </div>
          
          {/* Decorative Blob */}
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[120%] h-[120%] bg-indigo-500/20 blur-[80px] -z-10 rounded-full" />
        </motion.div>
      </div>
    </section>
  );
}
