import 'package:freezed_annotation/freezed_annotation.dart';

part 'generated_bill.freezed.dart';
part 'generated_bill.g.dart';

/// Maps the `generated_bills` Supabase table.
@freezed
class GeneratedBill with _$GeneratedBill {
  const factory GeneratedBill({
    required String id,
    @JsonKey(name: 'user_id') required String userId,
    @JsonKey(name: 'year_month') required String yearMonth,
    @JsonKey(name: 'service_ids') @Default([]) List<String> serviceIds,
    @Default({}) Map<String, dynamic> payload,
    @JsonKey(name: 'total_amount') @Default(0.0) double totalAmount,
    @JsonKey(name: 'currency') @Default('INR') String currency,
    @JsonKey(name: 'is_paid') @Default(false) bool isPaid,
    @JsonKey(name: 'paid_at') DateTime? paidAt,
    @JsonKey(name: 'payment_method') String? paymentMethod,
    @JsonKey(name: 'payment_note') String? paymentNote,
    @JsonKey(name: 'ai_model_used') String? aiModelUsed,
    @JsonKey(name: 'created_at') DateTime? createdAt,
    @JsonKey(name: 'updated_at') DateTime? updatedAt,
    @JsonKey(name: 'bill_title') String? billTitle,
    @JsonKey(name: 'pdf_url') String? pdfUrl,
    @JsonKey(name: 'email_sent') @Default(false) bool emailSent,
    @JsonKey(name: 'custom_note') String? customNote,
    @JsonKey(name: 'auto_generated') @Default(false) bool autoGenerated,
    @JsonKey(name: 'trigger_type') String? triggerType,
  }) = _GeneratedBill;

  factory GeneratedBill.fromJson(Map<String, dynamic> json) =>
      _$GeneratedBillFromJson(json);
}

/// Helpers to extract structured data from the JSONB `payload` field.
extension GeneratedBillPayload on GeneratedBill {
  /// AI-generated summary — stored as 'aiSummary' by backend (older bills: 'summary').
  String get summary =>
      payload['aiSummary'] as String? ??
      payload['summary'] as String? ??
      '';

  /// AI recommendations — stored under insights.recommendation.
  String get recommendations {
    final ins = payload['insights'] as Map<String, dynamic>?;
    return ins?['recommendation'] as String? ??
        payload['recommendations'] as String? ??
        '';
  }

  List<dynamic> get items => payload['items'] as List<dynamic>? ?? [];

  Map<String, dynamic>? get insights =>
      payload['insights'] as Map<String, dynamic>?;

  /// Delivery rate % — stored under insights.deliveryRate.
  double get deliveryRate {
    final ins = payload['insights'] as Map<String, dynamic>?;
    return (ins?['deliveryRate'] as num?)?.toDouble() ??
        (payload['delivery_rate'] as num?)?.toDouble() ??
        0.0;
  }

  /// True when this bill was enriched by AI (has a model).
  bool get isAiGenerated =>
      aiModelUsed != null && aiModelUsed!.isNotEmpty;

  /// Display label for bill generation source.
  String get generationLabel =>
      isAiGenerated ? 'YesBill AI Generated Bill' : 'YesBill Generated Bill';
}

/// Bill list item (lighter response for list views)
@freezed
class BillListItem with _$BillListItem {
  const factory BillListItem({
    required String id,
    @JsonKey(name: 'year_month') required String yearMonth,
    @JsonKey(name: 'total_amount') @Default(0.0) double totalAmount,
    @JsonKey(name: 'currency') @Default('INR') String currency,
    @JsonKey(name: 'is_paid') @Default(false) bool isPaid,
    @JsonKey(name: 'ai_model_used') String? aiModelUsed,
    @JsonKey(name: 'created_at') DateTime? createdAt,
    @JsonKey(name: 'bill_title') String? billTitle,
    @JsonKey(name: 'auto_generated') @Default(false) bool autoGenerated,
    @JsonKey(name: 'trigger_type') String? triggerType,
    @Default({}) Map<String, dynamic> payload,
    @JsonKey(name: 'paid_at') DateTime? paidAt,
    @JsonKey(name: 'payment_method') String? paymentMethod,
    @JsonKey(name: 'custom_note') String? customNote,
    @JsonKey(name: 'service_ids') @Default([]) List<String> serviceIds,
  }) = _BillListItem;

  factory BillListItem.fromJson(Map<String, dynamic> json) =>
      _$BillListItemFromJson(json);
}

/// Helpers to extract payload info from BillListItem.
extension BillListItemPayload on BillListItem {
  List<dynamic> get items => payload['items'] as List<dynamic>? ?? [];
  double get deliveryRate =>
      (payload['delivery_rate'] as num?)?.toDouble() ?? 0.0;
  int get deliveredCount {
    final itms = items;
    if (itms.isEmpty) return 0;
    return itms.fold<int>(0, (sum, item) {
      final row = (item as Map?)?.cast<String, dynamic>() ?? {};
      return sum + ((row['daysDelivered'] as num?)?.toInt() ?? 0);
    });
  }
  int get skippedCount {
    final itms = items;
    if (itms.isEmpty) return 0;
    return itms.fold<int>(0, (sum, item) {
      final row = (item as Map?)?.cast<String, dynamic>() ?? {};
      return sum + ((row['daysSkipped'] as num?)?.toInt() ?? 0);
    });
  }
}
